services:
  recipe-site-ui:
    build: ./UI
    container_name: recipe-site-nginx
    hostname: recipe-site-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Source Files
      - type: bind
        source: ./UI/Source_Files
        target: /var/www/html
        read_only: true
      # Nginx Snippets
      - type: bind
        source: ./UI/snippets
        target: /etc/nginx/snippets/
        read_only: true
      # Default Configuration
      - type: bind
        source: ./UI/default
        target: /etc/nginx/sites-available/default
        read_only: true
      # SSL
      - type: bind
        source: ./UI/ssl
        target: /etc/ssl
        read_only: true

  recipe-site-db:
    build: ./DB
    container_name: recipe-site-mysql
    hostname: recipe-site-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306" # host port:container port
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
